apiVersion: agent-os.dev/v1alpha1
kind: Agent
metadata:
  name: sample-agent
  namespace: default
  labels:
    category: sample
    runtime: agno
    version: v1
  annotations:
    description: "Sample agent for demonstration"
    author: "Agent OS Team"
spec:
  description: "A sample agent demonstrating Agent OS capabilities and spec validation"

  runtime:
    type: agno
    version: ">=0.1.0"
    config:
      timeout: 300
      retries: 3

  behavior:
    systemPrompt: |
      You are a helpful assistant that demonstrates Agent OS capabilities.
      You can answer questions, perform tasks, and use tools effectively.
      Always be clear, concise, and helpful in your responses.
    temperature: 0.7
    maxTokens: 2000
    model: "gpt-4"

  tools:
    - name: echo
      type: builtin
      description: "Echo back the input message"

    - name: calculator
      type: reference
      description: "Perform mathematical calculations"
      reference: "tools/calculator.tool.yaml"

    - name: web-search
      type: custom
      description: "Search the web for information"

  policies:
    - name: rate-limit
      enabled: true
      config:
        requestsPerMinute: 60

    - name: content-filter
      enabled: true
      config:
        blockedPatterns: ["sensitive-data", "private-info"]

    - name: cost-control
      enabled: false

status:
  phase: Draft
  lastValidated: null
